ol7:
  base: oraclelinux:7-slim
  setup:
  locale:
    - ENV LANG=en_US.UTF-8
  install: RUN yum install -y
  curl: curl
  which: which
  find:
  git: git
  source: java-1.8.0-openjdk-devel java-1.8.0-openjdk-openjfx java-atk-wrapper gcc libstdc++-static python ruby
  zlib: zlib-devel
  openssl: openssl-devel
  cext: gcc make
ubuntu1804:
  base: ubuntu:18.04
  setup:
    - RUN apt-get update
  locale:
    - RUN apt-get install -y locales
    - RUN locale-gen en_US.UTF-8
    - ENV LANG=en_US.UTF-8
  install: RUN apt-get install -y
  curl: curl
  which:
  find:
  git: git
  source: openjdk-8-jdk openjdk-8-source make gcc g++ python ruby
  zlib: libz-dev
  openssl: libssl-dev
  cext: gcc libxml2 make
ubuntu1604:
  base: ubuntu:16.04
  setup:
    - RUN apt-get update
  locale:
    - RUN apt-get install -y locales
    - RUN locale-gen en_US.UTF-8
    - ENV LANG=en_US.UTF-8
  install: RUN apt-get install -y
  curl: curl
  which:
  find:
  git: git
  source: openjdk-8-jdk openjdk-8-source make gcc g++ python ruby
  zlib: libz-dev
  openssl: libssl-dev
  cext: gcc libxml2 make
fedora28:
  base: fedora:28
  setup:
  locale:
    - ENV LANG=en_US.UTF-8
  install: RUN dnf install -y
  curl: curl
  git: git
  which: which
  find: findutils
  zlib: zlib-devel
  openssl: openssl-devel
  cext: gcc make
  source: file gcc-c++ python ruby rubygem-json
