ol7:
  base: oraclelinux:7-slim
  setup:
  locale:
    - ENV LANG=en_US.UTF-8
  curl:
    - RUN yum install -y curl
  which:
    - RUN yum install -y which
  find:
  git:
    - RUN yum install -y git
  source:
    - RUN yum install -y java-1.8.0-openjdk-devel java-1.8.0-openjdk-openjfx java-atk-wrapper gcc libstdc++-static python ruby
  images:
    - RUN yum install -y gcc
  jdk: openjdk1.8.0_181
  zlib:
    - RUN yum install -y zlib-devel
  openssl:
    - RUN yum install -y openssl-devel
  cext:
    - RUN yum install -y glibc-devel make
    - COPY llvm-3.8.0-ol7.tar.gz /opt
    - RUN cd /opt && tar -zxf llvm-3.8.0-ol7.tar.gz
    - ENV PATH=/opt/llvm-3.8.0-ol7/bin:$PATH
    - RUN echo "/opt/llvm-3.8.0-ol7/lib64" >> /etc/ld.so.conf.d/llvm-x86_64.conf && ldconfig
  cppext:
    - RUN yum install -y gcc
  rvm:
  post-install: false
ubuntu1804:
  base: ubuntu:18.04
  setup:
    - RUN apt-get update
  locale:
    - RUN apt-get install -y locales
    - RUN locale-gen en_US.UTF-8
    - ENV LANG=en_US.UTF-8
  curl:
    - RUN apt-get install -y curl
  which:
  find:
  git:
    - RUN apt-get install -y git  
  source:
    - RUN apt-get install -y openjdk-8-jdk openjdk-8-source make gcc g++ python ruby
  images:
    - RUN apt-get install -y gcc
  jdk: openjdk1.8.0_181
  zlib:
    - RUN apt-get install -y libz-dev
  openssl:
    - RUN apt-get install -y libssl-dev
  cext:
    - RUN apt-get install -y make clang llvm
  cppext:
    - RUN apt-get install -y libc++-dev libc++abi-dev
  rvm:
  post-install: true
ubuntu1604:
  base: ubuntu:16.04
  setup:
    - RUN apt-get update
  locale:
    - RUN apt-get install -y locales
    - RUN locale-gen en_US.UTF-8
    - ENV LANG=en_US.UTF-8
  curl:
    - RUN apt-get install -y curl
  which:
  find:
  git:
    - RUN apt-get install -y git  
  source:
    - RUN apt-get install -y openjdk-8-jdk openjdk-8-source make gcc g++ python ruby
  images:
    - RUN apt-get install -y gcc
  jdk: openjdk1.8.0_181
  zlib:
    - RUN apt-get install -y libz-dev
  openssl:
    - RUN apt-get install -y libssl-dev
  cext:
    - RUN apt-get install -y make clang llvm
  cppext:
    - RUN apt-get install -y libc++-dev
  rvm:
  post-install: false
fedora28:
  base: fedora:28
  setup:
  locale:
    - ENV LANG=en_US.UTF-8
  curl:
    - RUN dnf install -y curl
  git:
    - RUN dnf install -y git
  which:
    - RUN dnf install -y which
  find:
    - RUN dnf install -y findutils
  source:
    - RUN dnf install -y java-1.8.0-openjdk-devel java-1.8.0-openjdk-openjfx java-atk-wrapper make gcc libstdc++-static python ruby rubygem-json
  images:
    - RUN dnf install -y gcc
  jdk: openjdk1.8.0_181
  zlib:
    - RUN dnf install -y zlib-devel
  openssl:
    - RUN dnf install -y openssl-devel
  cext:
    - RUN dnf install -y make clang llvm
  cppext:
    - RUN dnf install -y libcxx-devel
    - RUN dnf install -y libcxx
  rvm:
    - RUN dnf install -y procps
  post-install: true
