name: Lint

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1.1.0
    - name: Install dependencies
      run: |
        sudo apt-get install libz-dev libssl-dev gcc libxml2 make file g++ python ruby ruby-dev
        sudo gem install rubocop -v 0.66.0
    - name: Install JVMCI
      run: tool/jt.rb install jvmci
    - name: Install mx
      run: tool/jt.rb mx --version
    - name: Install Graal
      run: tool/jt.rb mx sforceimports
    - name: Build
      run: tool/jt.rb build --env jvm
    - name: Lint
      env:
        CONTINUOUS_INTEGRATION: true
      run: tool/jt.rb lint
